[[redirects]]
from ="/*"
to = "index.html"
status = 200

[[redirects]]
from = "/resetpassword/*"
to = "https://www.rootz.website/resetpassword/:splat"
status = 301

[[redirects]]
from ="/*"
to = "https://www.rootz.website/pages/authentication/sign-in"
status = 200